### ISSUE TITLE
httpd does not work ProxyPassMatch

### ISSUE THREAD

**Issue by coolermen** [docker-library/httpd#121]
I use the docker image httpd:latest
need to make a connection to the container of the image defconjuan/docker-php-5.2:latest
for this, as I understand it is necessary to register the directive PProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://php:9000/usr/local/apache2/htdocs/coolermen.ru/$1 in httpd.conf.
and for this, enable LoadModule proxy_module modules/mod_proxy.so
As soon as I turn it on, the container stops working and I just can’t understand what needs to be fixed.

[docker-compose.txt](https://github.com/docker-library/httpd/files/2673517/docker-compose.txt)
<details>
<summary> docker-compose.yml </summary>

```yml
version: '2'

services:
# ------------------------------------------------------------- nginx --> http://nginx_host	
  nginx:
    image: coolermen/nginx:v3
    container_name: nginx_app
    hostname: nginx_host
#    restart: always
    ports:
      - 80:80
    volumes:
     - /docker/coolermen.ru/nginx/default.conf:/etc/nginx/conf.d/default.conf
     - /docker/coolermen.ru/nginx/coolermen.ru.conf:/etc/nginx/conf.d/coolermen.ru.conf
     - /docker/coolermen.ru/WWW/nginx_host:/usr/share/nginx/html
     - /docker/coolermen.ru/log/nginx:/var/log/nginx
    links: 
      - phpmyadmin
    networks:
      network_coolermen:
        ipv4_address: 192.168.200.100
# ------------------------------------------------------------- mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb_app
    hostname: mariadb_host
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwertyu1
    ports:
      - 3306:3306
    networks:
      network_coolermen:
        ipv4_address: 192.168.200.101
# ------------------------------------------------------------- phpmyadmin --> http://nginx_host/phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_app
    hostname: phpmyadmin_host
#    restart: always
    links: 
      - mariadb:db
    ports:
      - 8081:80
    volumes:
     - /docker/coolermen.ru/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    domainname: amd.docker
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: qwertyu1
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
#      PMA_ABSOLUTE_URI=http://amd.docker/phpmyadmin/
    networks:
      network_coolermen:
        ipv4_address: 192.168.200.102
    depends_on:
      - mariadb
# ------------------------------------------------------------- httpd
  httpd:
    image: httpd:latest
    container_name: httpd_app
    hostname: httpd_host
    links: 
      - mariadb:db
      - php
    ports:
      - 8082:80
    volumes:
      - /docker/coolermen.ru/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - /docker/coolermen.ru/WWW:/usr/local/apache2/htdocs
    networks:
      network_coolermen:
        ipv4_address: 192.168.200.103
    depends_on:
      - mariadb
      - php
# ------------------------------------------------------------- php-5.2
  php:
    image: defconjuan/docker-php-5.2:latest
    container_name: php52_app
    hostname: php52_host
    links: 
      - mariadb:db
    ports:
      - 8083:80
    volumes:
     - /docker/coolermen.ru/WWW:/usr/local/apache2/htdocs
     - /docker/coolermen.ru/php/php.ini:/usr/local/src/phpfarm/inst/current/etc/php.ini
     - /docker/coolermen.ru/php/php-fpm.conf:/usr/local/src/phpfarm/inst/current/etc/php-fpm.conf
    networks:
      network_coolermen:
        ipv4_address: 192.168.200.104
    depends_on:
      - mariadb
# ------------------------------------------------------------- networks 
networks:
 network_coolermen:
    driver: bridge
    ipam:
      driver: default
      config:
         - subnet: 192.168.200.0/24
           gateway: 192.168.200.1
```
</details>

[httpd.txt](https://github.com/docker-library/httpd/files/2673522/httpd.txt)
<details>
<summary> httpd </summary>

```console
ServerName localhost
Listen 80
#LogLevel error
#LogLevel notice
LogLevel debug
ErrorLog  /var/log/httpd_error_log.txt
CustomLog /var/log/CustomLog.txt common


<VirtualHost *:80>
    DocumentRoot /usr/local/apache2/htdocs/nginx_host
    ServerName nginx_host
	<Directory /usr/local/apache2/htdocs/nginx_host>
		AllowOverride All
		Require all granted
  </Directory>
</VirtualHost>



<VirtualHost *:80>
  ServerName coolermen.ru
  ServerAlias www.coolermen.ru
  ServerAdmin info@coolermen.ru
  DocumentRoot /usr/local/apache2/htdocs/coolermen.ru
  ErrorLog /usr/local/apache2/htdocs/coolermen.ru/logs/error.log
  CustomLog /usr/local/apache2/htdocs/coolermen.ru/logs/access.log combined

  ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://php:9000/usr/local/apache2/htdocs/coolermen.ru/$1
  

  <Directory /usr/local/apache2/htdocs/coolermen.ru>
    AllowOverride All
	Require all granted
  </Directory>
</VirtualHost>



LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule reqtimeout_module modules/mod_reqtimeout.so
LoadModule filter_module modules/mod_filter.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule version_module modules/mod_version.so

#LoadModule proxy_module modules/mod_proxy.so
#LoadModule proxy_http_module modules/mod_proxy_http.so

LoadModule unixd_module modules/mod_unixd.so
LoadModule status_module modules/mod_status.so
LoadModule autoindex_module modules/mod_autoindex.so
<IfModule !mpm_prefork_module>
	#LoadModule cgid_module modules/mod_cgid.so
</IfModule>
<IfModule mpm_prefork_module>
	#LoadModule cgi_module modules/mod_cgi.so
</IfModule>
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so

# by coolermen
```
</details>

**Comment by wglambert** [comment]
Can you give all the commands you ran and the `docker logs` output.

Since this doesn't seem to be an error with the image you could ask over at [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)

**Comment by coolermen** [comment]
httpd_app     | Invalid command 'ProxyPassMatch', perhaps misspelled or defined by a module not included in the server configuration

And if you turn on something new does not appear and the container does not work

root@debian:/docker/coolermen.ru# docker-compose restart httpd
Restarting httpd_app ... done
root@debian:/docker/coolermen.ru# docker-compose ps
     Name                   Command               State                      Ports
----------------------------------------------------------------------------------------------------
httpd_app        httpd-foreground                 Exit 1
mariadb_app      docker-entrypoint.sh mysqld      Up       0.0.0.0:3306->3306/tcp
nginx_app        nginx -g daemon off;             Up       0.0.0.0:80->80/tcp
php52_app        /src/entrypoint.sh run           Up       50022/tcp, 0.0.0.0:8083->80/tcp, 9000/tcp
phpmyadmin_app   /run.sh supervisord -n -j  ...   Up       0.0.0.0:8081->80/tcp, 9000/tcp
root@debian:/docker/coolermen.ru# docker-compose logs -f httpd
Attaching to httpd_app
httpd_app     | Invalid command 'ProxyPassMatch', perhaps misspelled or defined by a module not included in the server configuration
httpd_app exited with code 1
root@debian:/docker/coolermen.ru#

**Comment by wglambert** [comment]
>Invalid command 'ProxyPassMatch'

Looks like you didn't uncomment the modules in your config https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypassmatch

```
#LoadModule proxy_module modules/mod_proxy.so
#LoadModule proxy_http_module modules/mod_proxy_http.so
```

**Comment by coolermen** [comment]
If I do this, the container will not start. that's the problem

**Comment by wglambert** [comment]
Seems to be some sort of error in your config, have you tried it outside of a container environment? 
Using this config the container correctly `ProxyPassMatch`'s to http://testdomain when a *.php is referenced and gives a `[proxy:error]` for my domain.

<details>
<summary> httpd.conf </summary>

```console
ServerRoot "/usr/local/apache2"
Listen 80
<VirtualHost *:80>
ProxyPassMatch ^/(.*\.php(/.*)?)$ http://testdomain:80/usr/local/apache2/htdocs/$1
</VirtualHost>

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule reqtimeout_module modules/mod_reqtimeout.so
LoadModule filter_module modules/mod_filter.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule version_module modules/mod_version.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule status_module modules/mod_status.so
LoadModule autoindex_module modules/mod_autoindex.so
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so

<IfModule unixd_module>
User daemon
Group daemon
</IfModule>
ServerAdmin you@example.com
<Directory />
    AllowOverride none
    Require all denied
</Directory>
DocumentRoot "/usr/local/apache2/htdocs"
<Directory "/usr/local/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>
<Files ".ht*">
    Require all denied
</Files>
ErrorLog /proc/self/fd/2
LogLevel warn
<IfModule log_config_module>
    
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common
    <IfModule logio_module>
      
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>
    CustomLog /proc/self/fd/1 common
</IfModule>
<IfModule alias_module>
    ScriptAlias /cgi-bin/ "/usr/local/apache2/cgi-bin/"
</IfModule>
<IfModule cgid_module>
</IfModule>
<Directory "/usr/local/apache2/cgi-bin">
    AllowOverride None
    Options None
    Require all granted
</Directory>
<IfModule headers_module>
    
    RequestHeader unset Proxy early
</IfModule>
<IfModule mime_module>
    
    TypesConfig conf/mime.types
    
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
    
</IfModule>
<IfModule proxy_html_module>
Include conf/extra/proxy-html.conf
</IfModule>
<IfModule ssl_module>
SSLRandomSeed startup builtin
SSLRandomSeed connect builtin
</IfModule>
```
</details>

```yml
version: '2'
services:

  httpd:
    image: httpd:latest
    container_name: httpd_app
    hostname: httpd_host
    ports:
      - 8082:80
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
```
```console
$ docker-compose up
Creating network "httpd-121_default" with the default driver
Creating httpd_app ... done
Attaching to httpd_app
httpd_app | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.22.0.2. Set the 'ServerName' directive globally to suppress this message
httpd_app | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.22.0.2. Set the 'ServerName' directive globally to suppress this message
httpd_app | [Wed Dec 19 21:04:35.762814 2018] [mpm_event:notice] [pid 1:tid 139781794800832] AH00489: Apache/2.4.37 (Unix) configured -- resuming normal operations
httpd_app | [Wed Dec 19 21:04:35.762953 2018] [core:notice] [pid 1:tid 139781794800832] AH00094: Command line: 'httpd -D FOREGROUND'
^Z
[9]+  Stopped                 docker-compose up

$ curl http://localhost:8082/test.php
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/test.php">GET&nbsp;/test.php</a></em>.<p>
Reason: <strong>DNS lookup failure for: testdomain</strong></p></p>
</body></html>

$ docker-compose logs | tail -n 2
httpd_app | [Wed Dec 19 21:04:56.990387 2018] [proxy:error] [pid 12:tid 139781698270976] [client 172.22.0.1:53464] AH00898: DNS lookup failure for: testdomain returned by /test.php
httpd_app | 172.22.0.1 - - [19/Dec/2018:21:04:56 +0000] "GET /test.php HTTP/1.1" 502 397
```
