### ISSUE TITLE
container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by Tukks** [docker-library/httpd#179]
I currently using httpd in k8s :
```
volumeMounts:
            - name: httpd-conf
              mountPath: "/usr/local/apache2/conf/httpd.conf"
              subPath: httpd.conf
              readOnly: true
```

```
from {
    image 'httpd:2.4-alpine'
  }
  to {
    image = "$dockerBase/frontend:$dockerTag"

  }
  container {
    appRoot = '/usr/local/apache2/htdocs/'
  }
```
and I have this error : container has runAsNonRoot and image will run as root

Do you have any clue?

**Comment by wglambert** [comment]
You'll want to include a `runAsUser` in your `securityContext` to specify a non-root user (you'll want UID 33 for Debian's `www-data` user, if using Alpine then UID 82) . And then make a Dockerfile to apply a `setcap 'cap_net_bind_service=+ep' /usr/local/apache2/bin/httpd`

```dockerfile
FROM httpd
RUN apt update && apt install -y procps libcap2-bin && rm -rf /var/lib/apt/lists/*
RUN /sbin/setcap 'cap_net_bind_service=+ep' /usr/local/apache2/bin/httpd
RUN chown -hR www-data:www-data /usr/local/apache2/
USER www-data
```
httpd.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd
  name: httpd
spec:
  containers:
  - image: httpd:test
    name: httpd
    resources: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 33
```

```console
$ kubectl apply -f httpd.yaml
pod/httpd created

$ kubectl logs httpd
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.42.0.11. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.42.0.11. Set the 'ServerName' directive globally to suppress this message
[Fri May 07 16:23:47.997715 2021] [mpm_event:notice] [pid 1:tid 140700079944832] AH00489: Apache/2.4.47 (Unix) configured -- resuming normal operations
[Fri May 07 16:23:47.998091 2021] [core:notice] [pid 1:tid 140700079944832] AH00094: Command line: 'httpd -D FOREGROUND'

$ kubectl get po
NAME    READY   STATUS    RESTARTS   AGE
httpd   1/1     Running   0          14s

$ kubectl exec -it httpd -- bash

www-data@httpd:/usr/local/apache2$ echo $UID
33

www-data@httpd:/usr/local/apache2$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
www-data     1  0.0  0.2   5944  4296 ?        Ss   16:23   0:00 httpd -DFOREGROUND
www-data    10  0.0  0.3 751860  7504 ?        Sl   16:23   0:00 httpd -DFOREGROUND
www-data    11  0.0  0.3 751860  7508 ?        Sl   16:23   0:00 httpd -DFOREGROUND
www-data    12  0.0  0.2 751860  5468 ?        Sl   16:23   0:00 httpd -DFOREGROUND
www-data    94  0.0  0.1   3868  3184 pts/0    Ss   16:24   0:00 bash
www-data   100  0.0  0.1   7640  2656 pts/0    R+   16:24   0:00 ps aux
```
