### ISSUE TITLE
What is the `http-foreground` file?

### ISSUE THREAD

**Issue by boxxxie** [docker-library/httpd#20]
in the docker image it is obviously very important, as it's the last command that the iamge runs. i have no idea what should be in this file.

sorry, i am new to apache, i've only used nginx in the past, and i'm in a new project with very weak apache documentation and i'm trying to dockerize it.

i have a `docker-compose.yml` file with this config
```
version: "2"
services:
  apache:
    image: httpd:2.4
    volumes:
      - ./apache/staging/apache2:/usr/local/apache2/
    ports:
      - 80:80
```

when i run it i'm getting this error

```
apache_1 | /usr/local/bin/httpd-foreground: line 7: exec: httpd: not found
apache_1 exited with code 127
```
