### ISSUE TITLE
ERROR exec: httpd: not found

### ISSUE THREAD

**Issue by JavierSanchezCastro** [docker-library/httpd#225]
Hello! I'm getting this error when I try to up my docker-compose.

Honestly, it was working before and I don't know very well what I have modified.

Tree:
```bash
|- reverse-proxy
|  |- public-html
|     |- index.html
|  |- Dockerfile
|- docker-compose.yml
```

Dockerfile:
```
FROM httpd:2.4
COPY ./public-html/ /usr/local/apache2/htdocs/
```

docker-compose.yml
```
version: '3'
services:
  reverse-proxy:
    build: ./reverse-proxy
    container_name: reverse-proxy
```

Console Error
```console
reverse-proxy    | /usr/local/bin/httpd-foreground: 7: exec: httpd: not found
reverse-proxy exited with code 127
```

Any ideas? #20
