### ISSUE TITLE
a error

### ISSUE THREAD

**Issue by dongasai** [docker-library/httpd#90]
docker log:
2018-02-11 18:28:06:172.17.0.9 - - [11/Feb/2018:10:28:06 +0000] "GET / HTTP/1.1" 400 347
2018-02-11 18:28:06:172.17.0.9 - - [11/Feb/2018:10:28:06 +0000] "GET /favicon.ico HTTP/1.1" 400 347

web browser:
Bad Request
Your browser sent a request that this server could not understand.
Additionally, a 400 Bad Request error was encountered while trying to use an ErrorDocument to handle the request.

docker-compose.yml:
```yaml

httpd_wgjadmin:
  image: library/httpd:2.4.29
  privileged: false
  restart: always
  ports:
    - '80'
  volumes:
    - /docker/www/nodejs/wgj_admin/:/usr/local/apache2/htdocs/
```

Why is that?
