### ISSUE TITLE
Struggling to launch docker-compose because of Apache

### ISSUE THREAD

**Issue by Drillan767** [docker-library/httpd#92]
I'm setting up a docker image with docker-compose, Rails, Apache and MariaDB. However, when running `docker-compose up`, I get several messages that I don't know how to handle.

Here is my docker-compose file:

```
version: '3'
services:
  web:
    build: .
    entrypoint: bundle exec
    command: rails server -p 3000
    volumes:
      - .:/dockerails
    ports:
      - "3000"
    depends_on:
      - db
      - apache
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: epic_password
      MYSQL_DATABASE: dockerails
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  apache:
    image: httpd:alpine
    volumes:
      - ./docker/dockerails.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"
```

And Here is the Virtual Host:

```
<VirtualHost *:80>
  ServerName myname.me
  ServerAlias www.myname.me
  DocumentRoot /dockerails/public
  ErrorLog /usr/local/apache2/error/error.log
  LoadModule mpm_event_module modules/mod_mpm_event.so
  LoadModule authz_core_module modules/mod_authz_core.so
  <Directory "/dockerfile/public">
    Options FollowSymLinks
    Require all granted
  </Directory>
</VirtualHost>
```

When running docker-compose, the trace returns the following lines:

```
apache_1  | AH00112: Warning: DocumentRoot [/dockerails/public] does not exist
apache_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
apache_1  | no listening sockets available, shutting down
apache_1  | AH00015: Unable to open logs
```
For the first line, I don't really know how I should display the path nor if Apache can see "dockerails' structure
For the second, well, I think it's the least important of them all
For the 3rd line, when I type `sudo netstat -ltnp | grep ':80'`, nothing returns even while docker-compose is running. I might have forgotten something in the configuration file, but I wouldn't be able to tell what...
For the 4th line, I think it might be linked to the first line, even though I couldn't find anything log related on the official documentation

I'm sorry if this is a newbie question, I'm not used to Docker at all

Thank you in advance
