### ISSUE TITLE
Resolving container name in external network

### ISSUE THREAD

**Issue by babaorum** [docker-library/httpd#95]
Hi, I am having some trouble with apache while using an external network.
Here is my usecase : 

* I have a first docker compose which define an httpd, phpfpm, and mysql services 
```yaml
version: "2"

services:
    httpd:
        container_name: first_httpd
        image: httpd:2.4
        ports:
            - 8080:80

    phpfpm:
        container_name: first_phpfpm
        image: php:7.0-fpm

    mysql:
        container_name: only_mysql
        image: mysql:5.7
```

* I have a second docker compose which define an other docker-compose with the same apache and phpfpm. But the two needs to be able to talk to each other.
```yaml
version: "2"

services:
    httpd:
        container_name: second_httpd
        image: httpd:2.4
        ports:
            - 8081:80
        networks:
            - first_default
            - default

    phpfpm:
        container_name: second_phpfpm
        image: php:7.0-fpm
        networks:
            - first_default
            - default

networks:
    first_default:
        external: true
```

I use the external network feature to allow the needed services of my second docker compose to talk to the first one and vice-versa.

The **second_phpfpm** container can connect to the **only_mysql** without any issue (so the network feature is working great).
But when my **second_phpfpm** try making an http call to the **first_httpd** like so : http://first_httpd/my-url
I get an httpd error 400. I can see using docker logs that my **first_httpd** did receive the call. But it is not working.
The same http request send by **first_phpfpm**, will be resolved correctly.

The same problem occur when I try to call my **second_httpd** from my **first_phpfpm**.

My default vhost is quite simple : 
```
<VirtualHost *:80>

    <FilesMatch \.php$>
        SetHandler proxy:fcgi://first_phpfpm:9000
    </FilesMatch>

    DocumentRoot /www-data/public

    <Directory /www-data/public>

        # enable the .htaccess rewrites
        AllowOverride All
        Require all granted

        Options FollowSymlinks
        DirectoryIndex index.php

        <IfModule mod_rewrite.c>
            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ index.php [QSA,L]
        </IfModule>
    </Directory>

</VirtualHost>
```

Today, the only way I found to solve this is by checking the ip of the desired httpd container and using it directly in the http call. 
For exemple I connect to my **second_phpfpm** and ping **first_httpd** and if is use the same url as before with the ip it works.

I think there is an issue here ... Since it works for mysql, i think this is an httpd problem ...

Thank you for your time, I am quite struggling on this one ...
